### ISSUE TITLE
Version 2.0.0 not published to npm

### ISSUE THREAD

**Issue by waagdev** [sergiodxa/remix-auth-form#56]
Hello! First, I want to thank you for creating and maintaining remix-auth-form. It's a really valuable package!

I noticed that while the repository shows version 2.0.0, the latest version on npm is still 1.5.0.

Could you please publish the latest version to npm when possible?

Current versions:
- GitHub: v2.0.0
- npm: v1.5.0 (https://www.npmjs.com/package/remix-auth-form)

Thank you!

**Comment by natmfat** [comment]
arguably 2.0.0 would be published after the remix-auth dependency is upgraded to 4.0.0

**Comment by sergiodxa** [comment]
Seems v2 failed and I can't retry the GHA workflow, but v3 is now published and update to work with Remix Auth v4.
