### ISSUE TITLE
Feature: Bundle a hashing function

### ISSUE THREAD

**Issue by JacobParis** [sergiodxa/remix-auth-form#7]
Would it be worth providing a small hash function to the authenticate method?

This adds a bit of *opinion* about the right way to store passwords, but in this case I think a bit of well educated opinion would go a long way toward encouraging good security practices with a well chosen hash, like PBKDF2 which crypto-js supports (and is Cloudflare workers compliant)

```js
authenticate({ form, hash }) { }
```

**Comment by sergiodxa** [comment]
I would prefer to let the developer choose one, that way you could use crypt or crypto or crypto-js or the Cloudflare global crypto, it's up to the dev (or team) to choose what to do.

Personally, I think bcrypt is really good.
